### PR TITLE
Setup inital package

### PR DESCRIPTION
**Pull request by Michael-Teifel**
Co-authored-by: Kevin Lee <14950124+khobread@users.noreply.github.com>
Co-authored-by: Chacta Brice <74117562+StaticShock93@users.noreply.github.com>
Co-authored-by: Andrea Bennett <99983308+AndreaBennett42@users.noreply.github.com>

### CODE REVIEW

**Review by StaticShock93 — APPROVED** [review]
Looks good

**Review by khobread — APPROVED** [review]
Looks good! Thank you Michael

**Review by AndreaBennett42 — APPROVED** [review]

**Review by StaticShock93 — APPROVED** [review]
Looks good Michael

**Review by StaticShock93 — APPROVED** [review]
Nice job

**Review by khobread — APPROVED** [review]
Looks good!

**Pull request merged**
